---
- name: Restart Unbound
  command: "docker restart {{ item }}"
  with_items:
    - "{{ unbound_name }}"

- name: Remove Unbound
  command: "docker stop {{ item }} && docker rm {{ item }}"
  register: results
  with_items:
    - "{{ unbound_name }}"
  failed_when: >-
    results is failed and
    "No such container" not in results.stderr | default(false)
